name: Trigger WordPress Deployment

on:
  push:
    branches:
      - master

jobs:
  call-deploy:
    uses: ./.github/workflows/wordpress-deploy.yml
    with:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      ec2_public_ip: ${{ secrets.EC2_PUBLIC_IP }}
      github_token: ${{ secrets.PAT_TOKEN }}
