name: Trigger WordPress Deployment

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "The runner to execute the workflow on (e.g., ubuntu-latest, self-hosted)"
        required: true
        default: "ubuntu-latest"

jobs:
  call-deploy:
    uses: ./.github/workflows/wordpress-deploy.yml
    with:
      runner: ${{ inputs.runner }}  # Pass the runner input dynamically
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      ec2_public_ip: ${{ secrets.EC2_PUBLIC_IP }}
      pat: ${{ secrets.PAT_TOKEN }}
