name: Deploy WordPress to EC2

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
      ec2_public_ip:
        required: true
      pat:
        required: true
    inputs:
      runner:
        required: true
        type: string  # Accept the runner as a string input
     
jobs:
  deploy:
    runs-on: ${{ inputs.runner }}  # Dynamically use the runner input
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Add EC2 IP address to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ inputs.ec2_public_ip }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --exclude='.git' . ubuntu@${{ inputs.ec2_public_ip }}:/var/www/

      - name: Set correct permissions
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ inputs.ec2_public_ip }} "sudo chown ubuntu:ubuntu /var/www/"

      - name: Restart Apache
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ inputs.ec2_public_ip }} "sudo systemctl restart apache2"
