name: Deploy WordPress to EC2

on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
      ec2_public_ip:
        required: true
      pat:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH Key for EC2 access
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Install dependencies (scp, ssh)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Step 4: Extract WordPress files from latest.tar.gz
      - name: Extract WordPress
        run: |
          tar -xzvf latest.tar.gz

      # Step 5: Copy WordPress files to EC2 instance
      - name: Copy WordPress files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r wordpress/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/

      # Step 6: Set correct permissions for WordPress files
      - name: Set correct permissions
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo chown apache:apache /var/www/html/"

      # Step 7: Restart Apache service on EC2 to apply changes
      - name: Restart Apache
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart apache2"
